name: ConvergenceTesting

on:
   workflow_dispatch:
   schedule:
      - cron: '0 2 * * *'


jobs:
  #Run the convergence test on CoVo
  COVO_Conv:
    name: Velocity-Advection
    runs-on: ubuntu-latest
    env:
      {CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wunreachable-code"}
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{github.token}}
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - name: System Dependencies
      run: |
         .github/workflows/dependencies/dependencies.sh
         sudo apt-get install -y python3-setuptools
         python3 -m pip install --user numpy
         python3 -m pip install --user argparse
         python3 -m pip install --user matplotlib
    - name: Build AMReX Tools
      working-directory: ./Submodules/PelePhysics/Submodules/amrex/Tools/Plotfile
      run: |
        make
    - name: Build PeleLMeX
      working-directory: ./Exec/RegTests/PeriodicCases
      run: |
        make -j 2 TPL COMP=gnu
        make -j 2 COMP=gnu
    - name: Run
      working-directory: ./Exec/RegTests/PeriodicCases
      run: |
        cp ${GITHUB_WORKSPACE}/Submodules/PelePhysics/Submodules/amrex/Tools/Plotfile/fcompare.gnu.ex .
        sed -i "34s/.*/    resolution = [32,64,128,256,512]/" multiRuns.py
        sed -i "s/mpiexec -n 1/mpiexec -n 4 --oversubscribe/g" multiRuns.py
        ./multiRuns.py --test_name GH_CI_CoVo --input_file input.2d_CoVo
        sed -i "49s/.*/    resolution = [32,64,128,256,512]/" pprocConvOrder.py
        ./pprocConvOrder.py ./fcompare.gnu.ex --test_name GH_CI_CoVo
        cat Convergence_GH_CI_CoVo.dat
