name: unitTest

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-unitTest
  cancel-in-progress: true

jobs:
  # Build the RegTests/UnitTest
  UT_FS:
    name: UnitTest_FS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
    - name: System Dependencies
      run: |
          .github/workflows/dependencies/dependencies_gcc10.sh
          sudo apt-get install -y python3-setuptools
          python3 -m pip install --user numpy
          python3 -m pip install --user argparse
          python3 -m pip install --user matplotlib
    - name: LMeX Reference
      run: |
              mkdir buildRef
              git clone --recursive --single-branch --shallow-submodules -b development https://github.com/AMReX-Combustion/PeleLMeX.git buildRef/PeleLMeX
    - name: Build Reference PeleLMeX
      working-directory: ${{github.workspace}}/buildRef/PeleLMeX/Exec/UnitTests/DodecaneLu
      run: |
          make -j2 TPL COMP=gnu DEBUG=FALSE
          make -j2 COMP=gnu DEBUG=FALSE
    - name: Run Reference Case
      working-directory: ${{github.workspace}}/buildRef/PeleLMeX/Exec/UnitTests/DodecaneLu
      run: |
          ./PeleLMeX3d.gnu.MPI.ex inputs.3d
    - name: Reset Environment Variables
      run: |
              echo "AMREX_HOME=${{github.workspace}}/Submodules/PelePhysics/Submodules/amrex" >> $GITHUB_ENV
    - name: Build AMReX Tools
      working-directory: ${{env.AMREX_HOME}}/Tools/Plotfile
      run: |
          make -j2 VERBOSE=FALSE
    - name: Build PeleLMeX
      working-directory: ${{github.workspace}}/Exec/UnitTests/DodecaneLu
      run: |
          make -j2 TPL COMP=gnu DEBUG=FALSE
          make -j2 COMP=gnu DEBUG=FALSE
    - name: Run Case
      working-directory: ${{github.workspace}}/Exec/UnitTests/DodecaneLu
      run: |
          cp ${{env.AMREX_HOME}}/Tools/Plotfile/fcompare.gnu.ex .
          ./PeleLMeX3d.gnu.MPI.ex inputs.3d
          ./fcompare.gnu.ex pltEvaluate ${{github.workspace}}/buildRef/PeleLMeX/Exec/UnitTests/DodecaneLu/pltEvaluate
